{\rtf1\ansi\ansicpg1252\cocoartf2820
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 services:\
  directus:\
    image: directus/directus:11.2.1\
    ports:\
      - "8055"\
    volumes:\
      - DASHBOARD_database:/directus/database\
      - DASHBOARD_uploads:/directus/uploads\
      - DASHBOARD_extensions:/directus/extensions\
    environment:\
      SECRET: \'93put a secret here\'94\
      ADMIN_EMAIL: \'93admin@example.com\'94\
      ADMIN_PASSWORD: \'93Password\'94\
      DB_CLIENT: "sqlite3"\
      DB_FILENAME: "/directus/database/data.db"\
      WEBSOCKETS_ENABLED: "true"\
\
      PUBLIC_URL: \'93put your directus url here\'94\
      \
      REFRESH_TOKEN_COOKIE_SECURE: "true"\
      REFRESH_TOKEN_COOKIE_SAME_SITE: "None"\
      \
      SESSION_COOKIE_DOMAIN: \'93put your base domain here\'94\
      SESSION_COOKIE_SECURE: "true"\
      SESSION_COOKIE_SAME_SITE: "None"\
\
      \
      CORS_ENABLED: true\
      CORS_ORIGIN: \'93put your prod url here\'93\
\
volumes:\
  DASHBOARD_database:\
  DASHBOARD_uploads:\
  DASHBOARD_extensions:}